name: Deploy Docs
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "Successfully completed"

      - name: The docs
        run: |
         echo "feedback"
         echo "meeting"
         shell: bash      

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.AICMM }}
          publish_dir: ./dist
